db.placement_questions.deleteMany({});

db.placement_questions.insertMany([
  { _id: "q1",  questionType: "MULTIPLE_CHOICE", category: "grammar", question: "She ___ to school every day.", options: ["go", "goes", "going", "gone"], correctAnswer: "goes", explanation: "Third person singular takes -s.", orderNo: 1 },
  { _id: "q2",  questionType: "MULTIPLE_CHOICE", category: "grammar", question: "They ___ dinner now.", options: ["have", "having", "are having", "had"], correctAnswer: "are having", explanation: "Present continuous for action happening now.", orderNo: 2 },
  { _id: "q3",  questionType: "MULTIPLE_CHOICE", category: "grammar", question: "I ___ my homework yesterday.", options: ["do", "did", "done", "am doing"], correctAnswer: "did", explanation: "Past simple with yesterday.", orderNo: 3 },
  { _id: "q4",  questionType: "MULTIPLE_CHOICE", category: "grammar", question: "If it rains, we ___ at home.", options: ["stay", "will stay", "stayed", "staying"], correctAnswer: "will stay", explanation: "First conditional.", orderNo: 4 },
  { _id: "q5",  questionType: "MULTIPLE_CHOICE", category: "grammar", question: "This book is ___ than that one.", options: ["interesting", "more interesting", "most interesting", "interested"], correctAnswer: "more interesting", explanation: "Comparative form.", orderNo: 5 },
  { _id: "q6",  questionType: "MULTIPLE_CHOICE", category: "grammar", question: "He has lived here ___ 2020.", options: ["for", "since", "from", "at"], correctAnswer: "since", explanation: "Use since with a starting point.", orderNo: 6 },
  { _id: "q7",  questionType: "MULTIPLE_CHOICE", category: "grammar", question: "By next year, I ___ my degree.", options: ["finish", "finished", "will have finished", "am finishing"], correctAnswer: "will have finished", explanation: "Future perfect.", orderNo: 7 },
  { _id: "q8",  questionType: "MULTIPLE_CHOICE", category: "grammar", question: "The car ___ yesterday.", options: ["was repaired", "repaired", "is repair", "has repair"], correctAnswer: "was repaired", explanation: "Passive voice in past simple.", orderNo: 8 },
  { _id: "q9",  questionType: "MULTIPLE_CHOICE", category: "grammar", question: "She asked me where I ___ from.", options: ["am", "was", "were", "be"], correctAnswer: "was", explanation: "Reported speech backshift.", orderNo: 9 },
  { _id: "q10", questionType: "MULTIPLE_CHOICE", category: "grammar", question: "I wish I ___ more free time.", options: ["have", "had", "will have", "am having"], correctAnswer: "had", explanation: "Wish + past simple for present unreal situations.", orderNo: 10 },

  { _id: "q11", questionType: "MULTIPLE_CHOICE", category: "vocabulary", question: "A person who designs buildings is an ___.", options: ["engineer", "architect", "accountant", "artist"], correctAnswer: "architect", explanation: "Architect designs buildings.", orderNo: 11 },
  { _id: "q12", questionType: "MULTIPLE_CHOICE", category: "vocabulary", question: "The opposite of 'cheap' is ___.", options: ["small", "expensive", "broken", "weak"], correctAnswer: "expensive", explanation: "Opposite meaning.", orderNo: 12 },
  { _id: "q13", questionType: "MULTIPLE_CHOICE", category: "vocabulary", question: "If something is 'essential', it is ___.", options: ["optional", "necessary", "dangerous", "boring"], correctAnswer: "necessary", explanation: "Essential means necessary.", orderNo: 13 },
  { _id: "q14", questionType: "MULTIPLE_CHOICE", category: "vocabulary", question: "We need to ___ a decision soon.", options: ["do", "make", "take off", "bring"], correctAnswer: "make", explanation: "Collocation: make a decision.", orderNo: 14 },
  { _id: "q15", questionType: "MULTIPLE_CHOICE", category: "vocabulary", question: "He was very ___ after running 10 kilometers.", options: ["tired", "hungryly", "careful", "cheap"], correctAnswer: "tired", explanation: "Correct adjective by context.", orderNo: 15 },
  { _id: "q16", questionType: "MULTIPLE_CHOICE", category: "vocabulary", question: "The meeting was ___ because the manager was ill.", options: ["cancelled", "improved", "repaired", "trained"], correctAnswer: "cancelled", explanation: "Meeting can be cancelled.", orderNo: 16 },
  { _id: "q17", questionType: "MULTIPLE_CHOICE", category: "vocabulary", question: "She speaks English ___.", options: ["fluent", "fluently", "fluency", "more fluent"], correctAnswer: "fluently", explanation: "Adverb modifies speaks.", orderNo: 17 },
  { _id: "q18", questionType: "MULTIPLE_CHOICE", category: "vocabulary", question: "A ___ is a place where you can borrow books.", options: ["library", "bakery", "factory", "museum"], correctAnswer: "library", explanation: "Library is for borrowing books.", orderNo: 18 },
  { _id: "q19", questionType: "MULTIPLE_CHOICE", category: "vocabulary", question: "The company wants to ___ its sales this year.", options: ["reduce", "increase", "forget", "translate"], correctAnswer: "increase", explanation: "Increase sales.", orderNo: 19 },
  { _id: "q20", questionType: "MULTIPLE_CHOICE", category: "vocabulary", question: "He gave a very ___ explanation, so everyone understood.", options: ["confusing", "clear", "illegal", "rare"], correctAnswer: "clear", explanation: "Clear explanation fits context.", orderNo: 20 },

  { _id: "q21", questionType: "MULTIPLE_CHOICE", category: "reading", question: "Tom missed the bus because he woke up late. Why did Tom miss the bus?", options: ["The bus was cancelled", "He woke up late", "He forgot his bag", "It was raining"], correctAnswer: "He woke up late", explanation: "Direct detail question.", orderNo: 21 },
  { _id: "q22", questionType: "MULTIPLE_CHOICE", category: "reading", question: "Anna studies every evening because she wants to pass the exam. Why does Anna study every evening?", options: ["She enjoys TV", "She wants to pass the exam", "She is bored", "Her friend told her"], correctAnswer: "She wants to pass the exam", explanation: "Purpose is explicitly stated.", orderNo: 22 },
  { _id: "q23", questionType: "MULTIPLE_CHOICE", category: "reading", question: "The weather was cold, so they stayed inside. Why did they stay inside?", options: ["They were working", "They were tired", "The weather was cold", "They had guests"], correctAnswer: "The weather was cold", explanation: "Cause is given.", orderNo: 23 },
  { _id: "q24", questionType: "MULTIPLE_CHOICE", category: "reading", question: "The museum opens at 9 a.m. and closes at 5 p.m. When does it close?", options: ["At 9 a.m.", "At noon", "At 5 p.m.", "At 6 p.m."], correctAnswer: "At 5 p.m.", explanation: "Explicit detail.", orderNo: 24 },
  { _id: "q25", questionType: "MULTIPLE_CHOICE", category: "reading", question: "Lisa bought apples, bananas, and oranges. What did Lisa buy?", options: ["Vegetables", "Books", "Fruit", "Clothes"], correctAnswer: "Fruit", explanation: "All listed items are fruit.", orderNo: 25 },
  { _id: "q26", questionType: "MULTIPLE_CHOICE", category: "reading", question: "Mark didn't go to the party because he was sick. Why didn't Mark go to the party?", options: ["He was busy", "He was sick", "He forgot", "He was traveling"], correctAnswer: "He was sick", explanation: "Reason is stated.", orderNo: 26 },
  { _id: "q27", questionType: "MULTIPLE_CHOICE", category: "reading", question: "The new phone is lighter and faster than the old one. Which is true?", options: ["The old phone is faster", "The new phone is lighter", "Both phones are heavy", "The new phone is slower"], correctAnswer: "The new phone is lighter", explanation: "Comparison detail.", orderNo: 27 },
  { _id: "q28", questionType: "MULTIPLE_CHOICE", category: "reading", question: "Sarah took an umbrella, although the sky was clear. What did Sarah take?", options: ["A coat", "An umbrella", "A ticket", "A map"], correctAnswer: "An umbrella", explanation: "Explicit detail.", orderNo: 28 },
  { _id: "q29", questionType: "MULTIPLE_CHOICE", category: "reading", question: "The article says regular exercise improves both mood and health. What improves mood and health?", options: ["Travel", "Regular exercise", "Reading fiction", "Coffee"], correctAnswer: "Regular exercise", explanation: "Main idea/detail.", orderNo: 29 },
  { _id: "q30", questionType: "MULTIPLE_CHOICE", category: "reading", question: "Although the task was difficult, the team finished it on time. Which is true?", options: ["The team failed", "The task was easy", "The team finished on time", "They started late"], correctAnswer: "The team finished on time", explanation: "Explicit detail.", orderNo: 30 }
]);